apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler 
metadata:
    name: ml-server-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1 
        kind: Deployment 
        name: ml-server-deployment
    minReplicas: 1 
    maxReplicas: 20
    targetCPUUtilizationPercentage: 50