apiVersion: apps/v1
kind: Deployment
metadata:
    name: ml-server-deployment
spec:
    replicas: 10
    selector:
        matchLabels:
            component: ml-service
    template:
        metadata:
            labels:
                component: ml-service
        spec:
            containers:
            - image: bogdanp3trovic/ml-server:2.4
              name: ml-server
              ports:
                - containerPort: 8000
              resources:
                  requests:
                      cpu: "250m"
              volumeMounts:
                - name: model-storage
                  mountPath: /app/model
                  readOnly: true
            volumes:
              - name: model-storage
                persistentVolumeClaim:
                    claimName: ml-service-pv-claim
                    readOnly: true
